/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scenario.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scenario.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.326, 0]} scale={[5.204, 1.232, 5.204]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.007']} position={[-7.561, 2.783, 3.618]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.732, -0.966, -0.732]} />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.008']} position={[-7.529, 1.654, 3.614]} scale={[1, 0.957, 1]} />
      <mesh geometry={nodes.BezierCurve.geometry} material={materials['Material.004']} position={[-0.069, -1.591, -0.222]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.005']} position={[3.794, 2.817, -12.565]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.732, -0.966, -0.732]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.006']} position={[3.826, 1.707, -12.569]} scale={[1, 0.957, 1]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.009']} position={[-8.248, 2.817, -12.565]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.732, -0.966, -0.732]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.010']} position={[-8.216, 1.707, -12.569]} scale={[1, 0.957, 1]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.011']} position={[-2.56, 2.817, -12.565]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.732, -0.966, -0.732]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.012']} position={[-2.529, 1.707, -12.569]} scale={[1, 0.957, 1]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.013']} position={[-2.56, 2.817, 3.805]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.732, -0.966, -0.732]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.014']} position={[-2.529, 1.707, 3.801]} scale={[1, 0.957, 1]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.015']} position={[3.883, 2.817, 3.805]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.732, -0.966, -0.732]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.016']} position={[3.914, 1.707, 3.801]} scale={[1, 0.957, 1]} />
      <mesh geometry={nodes.BezierCurve001.geometry} material={materials['Material.017']} position={[-2.737, -0.142, 0]} />
      <mesh geometry={nodes.BezierCurve002.geometry} material={materials['Material.018']} position={[0, -0.426, 0]} />
    </group>
  )
}

useGLTF.preload('/scenario.gltf')
